### ISSUE TITLE
File io.github.coalangsoft.lib, io.github.coalangsoft.visit and io.github.coalangsoft.visitfx are not included

### ISSUE THREAD

**Issue by David-Kyrat** [coalang-soft/dragdropfx#1]
Some dependencies are missing to run the test `test.dragdropfx.DragDropTest`.
See img uploaded below.

<img width="412" alt="image" src="https://user-images.githubusercontent.com/33601938/147393859-e712f7f7-cce2-4769-b80a-431368269f04.png">
 
<img width="554" alt="image" src="https://user-images.githubusercontent.com/33601938/147393875-a239094a-fcef-4e0d-9b38-a5b600b77a14.png">

**Comment by NetLamp-Y** [comment]
Thank you for opening an issue about this - that problem should be fixed now :)
If you want to try if it does indeed work on your system, that would be very much appreciated.
